version: "3.9"
services:
  c4viz:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - "c4vizcache:/var/cache/c4viz"
      # - "./sourceDir:/sourceDir"
    environment:
      SERVER_PORT: "9000"
      C4VIZ_SOURCE: big-bank-plc.dsl
      # Already the default
      # C4VIZ_SOURCE_DIR: /sourceDir
volumes:
  c4vizcache: {}

